spring:
  application:
    name: Smartbiz-App

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}   # Defaults to 'localhost' if REDIS_HOST is not set
      port: ${REDIS_PORT:6379}        # Defaults to '6379' if REDIS_PORT is not set
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method

cloudinary:
  cloud_name: ${cloud_name}
  api_key: ${cloudinary_api_key}
  api_secret: ${cloudinary_api_secret}
stripe:
  publishable_key: ${stripe_publishable_key}
  secret_key: ${stripe_secret}
